export default {
  LATEST_ZVEK: 'Latest SE Damage, B',
  DAMAGE: 'Damage',
  NICKNAME: 'Nickname',
  BILLION: 'B',
  BACK: 'Back',
  ERROR: 'Something went wrong:',
  TRY: 'Try again',
  TUE: 'Tue',
  WED: 'Wed',
  THU: 'Thu',
  FRI: 'Fri',
  SAT: 'Sat',
  SUN: 'Sun',
  LAST: 'Last SE',
  STAT: 'Statistics',
  CONTACTS: 'Contacts',
  NO_DATA: 'No data',
  GROW: 'SE change',
  GUILD_RATING: 'Guild rating',
  NEWBIES: 'Newbies',
  ADMIN_TITLE: 'Admin panel',
  ADMIN_ENTER: 'Login to Admin Panel',
  ERROR_DATA: 'Incorrect login or password',
  LOGIN: 'Login',
  PASSWORD: 'Password',
  ENTER: 'Login',
  LOGOUT: 'Logout',
  USERS: 'Active users',
  SE_DATA: 'SE data',
};
