export default {
  LATEST_ZVEK: 'Урон последнего ЗВЭК, млрд',
  DAMAGE: 'Урон',
  NICKNAME: 'Никнейм',
  BILLION: 'млд',
  BACK: 'Назад',
  ERROR: 'Что-то пошло не так:',
  TRY: 'Попробуйте снова',
  TUE: 'Вт',
  WED: 'Ср',
  THU: 'Чт',
  FRI: 'Пт',
  SAT: 'Сб',
  SUN: 'Вс',
  LAST: 'Последний ЗВЭК',
  STAT: 'Статистика',
  CONTACTS: 'Контакты',
  NO_DATA: 'Нет данных',
  GROW: 'Звэк движение',
  GUILD_RATING: 'Место гильдии в рейтинге',
  NEWBIES: 'Новые игроки',
  ADMIN_TITLE: 'Админ панель',
  ADMIN_ENTER: 'Вход в Админку',
  ERROR_DATA: 'Неверный логин или пароль',
  LOGIN: 'Логин',
  PASSWORD: 'Пароль',
  ENTER: 'Войти',
  LOGOUT: 'Выйти',
  USERS: 'Активные юзеры',
  SE_DATA: 'Данные ЗВЕК',
};
