export default {
  LATEST_ZVEK: 'Урон останнього ЗВЭК, млрд',
  DAMAGE: 'Урон',
  NICKNAME: 'Нікнейм',
  BILLION: 'млд',
  BACK: 'Назад',
  ERROR: 'Щось пішло не так:',
  TRY: 'Спробуйте знову',
  TUE: 'Вт',
  WED: 'Ср',
  THU: 'Чт',
  FRI: 'Пт',
  SAT: 'Сб',
  SUN: 'Нд',
  LAST: 'Останній ЗВЕК',
  STAT: 'Статистика',
  CONTACTS: 'Контакти',
  NO_DATA: 'Немає даних',
  GROW: 'Звек рух',
  GUILD_RATING: 'Місце гільдії в рейтингу',
  NEWBIES: 'Нові гравці',
};
