export default {
  LATEST_ZVEK: 'Урон останнього ЗВЭК, млрд',
  DAMAGE: 'Урон',
  NICKNAME: 'Нікнейм',
  QUALITY: 'Якість',
  TEMPLE: 'Храм',
  HERO: 'Герой',
  STARS: 'Зірки',
  CREATE: 'Створено',
  UPDATE: 'Оновлено',
  STATUS: 'Статус',
  BILLION: 'млд',
  BACK: 'Назад',
  ERROR: 'Щось пішло не так:',
  TRY: 'Спробуйте знову',
  TUE: 'Вт',
  WED: 'Ср',
  THU: 'Чт',
  FRI: 'Пт',
  SAT: 'Сб',
  SUN: 'Нд',
  LAST: 'Останній ЗВЕК',
  STAT: 'Статистика',
  CONTACTS: 'Контакти',
  NO_DATA: 'Немає даних',
  GROW: 'Звек рух',
  GUILD_RATING: 'Місце гільдії в рейтингу',
  NEWBIES: 'Нові гравці',
  ADMIN_TITLE: 'Адмін панель',
  ADMIN_ENTER: 'Вхід до Адмінки',
  ERROR_DATA: 'Неправильний логін або пароль',
  LOGIN: 'Логін',
  PASSWORD: 'Пароль',
  ENTER: 'Увійти',
  LOGOUT: 'Вийти',
  USERS: 'Активні користувачі',
  SE_DATA: 'Дані ЗВЕК',
  DATA: 'Дата',
  TOTAL: 'Урон гільдії',
  RATE: 'Рейтинг',
  NEW: 'Новички',
  SAVE: 'Зберегти зміни',
  CREATE_ENTITY: 'Створити',
  ADD: 'Додати',
  EDIT: 'Редагування',
  DELETE: 'Видалити',
  DATE_ERR: 'Неправильний формат дати',
  DATE_HINT: 'Формат: ММ.РР (наприклад, 08.26)',
};
