export default {
  TOP_PLAYERS: 'Top players of last SEs',
  DAMAGE_DECREASE: 'Damage decrease',
  ZERO_DAMAGE: 'Zero damage at last SE',
  JINNI_COEF: 'Disbalance factor',
  FORMULA: 'Equation:',
  WHERE: 'where',
  COUNT: '— number of players.',
  DAMAGE: '— player`s damage',
  AVERAGE_DAMAGE: '— average damage',
  AVERAGE_COUNT: 'arithmetic average',
  SMALL: '0.2−0.3: Damage is distributed fairly evenly.',
  MEDIUM:
    '0.5: Moderate inequality. There are a few players with significantly larger contributions, but the others also make a noticeable impact.',
  HARD: '0.8−1.0: Severe inequality. Damage is mainly concentrated among one or a few "top" players, while the rest have almost no impact on the overall result.',
  DATE: 'Date',
  TOP: 'Top 1,2,3',
  PERCENT: '% of overall damage',
  JINNI: 'The Gini coefficient.',
  DAMAGE_GUILD: 'Guild damage, B',
  CHANGES: 'Changes',
  INCREASE: 'Increased by',
  DECREASE: 'Decreased by',
  DAY: 'Day',
  LAST_ZVEK: 'Last SE Damage, T',
  ALL_PLAYERS_HAVE_DAMAGED: 'All players damaged in all days',
};
